### ISSUE TITLE
Project CloudFormation Stack can't be deleted because `S3Artifact` bucket is not empty

### ISSUE THREAD

**Issue by acere** [aws-samples/amazon-sagemaker-drift-detection#10]
When deleting the CloudFormation Stack created by the project, the process fails because  `S3Artifact` bucket contains objects and can't be deleted.

**Comment by brightsparc** [comment]
The notebook provides a script to delete the versioned S3 objects before deleting the bucket which then allows you to delete the bucket.

**Comment by acere** [comment]
Then the script to delete the versioned S3 objects needs to be run before deleting the CloudFormation stacks. I would suggest reordering these two cells.
