### ISSUE TITLE
Pipelines failed to deploy

### ISSUE THREAD

**Issue by Changshama** [aws-samples/amazon-sagemaker-drift-detection#25]
Both CloudFormation and manual deploy failed to deploy the pipeline.

I saw the following from Cloudwatch,

npm WARN notsup Unsupported engine for [aws-cdk@2.53.0](mailto:aws-cdk@2.53.0): wanted: { "node": ">= 14.15.0" } (current: { "node": "12.22.12", "npm": "6.14.16" } )

Looks like it is relevant to a CDK v1 bug as discussed in this thread https://github.com/aws/aws-cdk/issues/20739

Have tried migrating to CDK v2 but not got the issue solved yet. @acere can you please share some insights on this end?

**Comment by acere** [comment]
@Changshama the issue should be addressed by the pull request above
